// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jFJFziXZKhcspnrEU1bpXe
// Component: Dne9SssEBVU

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Analytics from "../../Analytics"; // plasmic-import: n519WuZQnL/component
import PageHeader from "../../PageHeader"; // plasmic-import: eDzLCW1ZjEb/component
import NavBar from "../../NavBar"; // plasmic-import: 5wmWvgxHSq/component
import PageFooter from "../../PageFooter"; // plasmic-import: MxvU_cyYFXz/component

import { useScreenVariants as useScreenVariantsyX0GVx02K4UjjJ } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: yX0gVX02K4ujjJ/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: jFJFziXZKhcspnrEU1bpXe/projectcss
import sty from "./PlasmicTos.module.css"; // plasmic-import: Dne9SssEBVU/css

createPlasmicElementProxy;

export type PlasmicTos__VariantMembers = {};
export type PlasmicTos__VariantsArgs = {};
type VariantPropType = keyof PlasmicTos__VariantsArgs;
export const PlasmicTos__VariantProps = new Array<VariantPropType>();

export type PlasmicTos__ArgsType = {};
type ArgPropType = keyof PlasmicTos__ArgsType;
export const PlasmicTos__ArgProps = new Array<ArgPropType>();

export type PlasmicTos__OverridesType = {
  root?: Flex__<"div">;
  analytics?: Flex__<typeof Analytics>;
  pageHeader?: Flex__<typeof PageHeader>;
  navBar?: Flex__<typeof NavBar>;
  pageFooter?: Flex__<typeof PageFooter>;
};

export interface DefaultTosProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTos__RenderFunc(props: {
  variants: PlasmicTos__VariantsArgs;
  args: PlasmicTos__ArgsType;
  overrides: PlasmicTos__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsyX0GVx02K4UjjJ()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <Analytics
            data-plasmic-name={"analytics"}
            data-plasmic-override={overrides.analytics}
            className={classNames("__wab_instance", sty.analytics)}
          />

          <section className={classNames(projectcss.all, sty.section___8Mvfp)}>
            <section className={classNames(projectcss.all, sty.section__ycp4P)}>
              <PageHeader
                data-plasmic-name={"pageHeader"}
                data-plasmic-override={overrides.pageHeader}
                className={classNames("__wab_instance", sty.pageHeader)}
              />

              {(
                hasVariant(globalVariants, "screen", "smallMobile")
                  ? true
                  : hasVariant(globalVariants, "screen", "mobileOnly")
                  ? true
                  : false
              ) ? (
                <NavBar
                  data-plasmic-name={"navBar"}
                  data-plasmic-override={overrides.navBar}
                  className={classNames("__wab_instance", sty.navBar)}
                />
              ) : null}
              <section
                className={classNames(projectcss.all, sty.section__lYlZ)}
              />

              <section
                className={classNames(projectcss.all, sty.section__lqlBr)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__s0Jjx
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#FFFFFF" }}
                    >
                      {"Terms of Service"}
                    </span>
                  </React.Fragment>
                </div>
                <section
                  className={classNames(projectcss.all, sty.section___6N5F)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fgxV7
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {"Effective Date: 05/31/2023"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          'These Terms of Service ("Terms") govern your use of the Red Crown website and any related services, applications, or features (collectively referred to as the "Services") provided by Red Crown ("we," "us," or "our"). By accessing or using our Services, you agree to be bound by these Terms. If you do not agree with these Terms, please do not access or use our Services.'
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {"1. Use of Services"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "1.1 Eligibility: You must be at least 18 years old or the age of legal majority in your jurisdiction to use our Services. By using our Services, you represent and warrant that you meet the eligibility requirements."
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "1.2 User Account: In order to access certain features or areas of our Services, you may be required to create a user account. You are responsible for maintaining the confidentiality of your account information, including your username and password, and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account or any other breach of security."
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "1.3 Prohibited Activities: When using our Services, you agree not to:"
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "(a) Violate any applicable laws, regulations, or third-party rights;"
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "(b) Use our Services for any unlawful, fraudulent, or malicious purpose;"
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "(c) Interfere with or disrupt the integrity or performance of our Services or the data contained therein;"
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "(d) Attempt to gain unauthorized access to our Services, user accounts, or computer systems;"
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "(e) Engage in any activity that could harm or negatively affect our reputation or the reputation of our Services;"
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "(f) Use any automated means or interface to access our Services or extract data from our Services;"
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "(g) Impersonate any person or entity or falsely state or otherwise misrepresent your affiliation with a person or entity."
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {"2. Intellectual Property Rights"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "2.1 Ownership: All content, materials, and features available on our Services, including but not limited to text, graphics, logos, images, audio clips, videos, and software, are the property of Red Crown or our licensors and are protected by applicable intellectual property laws."
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "2.2 License: Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, and revocable license to access and use our Services for personal, non-commercial purposes. You may not modify, reproduce, distribute, create derivative works of, publicly display, or publicly perform any content or materials from our Services unless expressly authorized by us."
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {"3. Limitation of Liability"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "To the maximum extent permitted by applicable law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or business opportunities, arising out of or in connection with your use of our Services."
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {"4. Third-Party Links"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "Our Services may contain links to third-party websites or resources that are not owned or controlled by us. We are not responsible for the content, privacy policies, or practices of any third-party websites. We recommend that you review the terms and privacy policies of any third-party websites you visit."
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {"5. Modifications to the Services"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "We reserve the right to modify, suspend, or discontinue all or part of our Services at any time without prior notice or liability."
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {"6. Governing Law"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "These Terms shall be governed by and construed in accordance with the laws of [insert governing jurisdiction]. Any legal actions or proceedings arising out of or relating to these Terms shall be exclusively brought in the courts of [insert jurisdiction]."
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {"7. Changes to these Terms"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "We may revise these Terms at any time by posting the updated version on our website. Your continued use of our Services after any such changes constitutes your acceptance of the revised Terms."
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {"8. Contact Us"}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "If you have any questions or concerns about these Terms or our Services, please contact us via email at RedCrownRaleigh@gmail.com."
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "By using our Services, you acknowledge that you have read, understood, and agreed to these Terms."
                        }
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {""}
                      </span>
                      <React.Fragment>{"\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FEFEFE" }}
                      >
                        {
                          "Please note that these Terms of Service apply only to your use of our Services and do not govern any other interactions or relationships you may have with Red Crown offline or through other channels."
                        }
                      </span>
                    </React.Fragment>
                  </div>
                </section>
                <PageFooter
                  data-plasmic-name={"pageFooter"}
                  data-plasmic-override={overrides.pageFooter}
                  className={classNames("__wab_instance", sty.pageFooter)}
                />
              </section>
            </section>
          </section>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "analytics", "pageHeader", "navBar", "pageFooter"],
  analytics: ["analytics"],
  pageHeader: ["pageHeader"],
  navBar: ["navBar"],
  pageFooter: ["pageFooter"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  analytics: typeof Analytics;
  pageHeader: typeof PageHeader;
  navBar: typeof NavBar;
  pageFooter: typeof PageFooter;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTos__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTos__VariantsArgs;
    args?: PlasmicTos__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTos__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicTos__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTos__ArgProps,
          internalVariantPropNames: PlasmicTos__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTos__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTos";
  } else {
    func.displayName = `PlasmicTos.${nodeName}`;
  }
  return func;
}

export const PlasmicTos = Object.assign(
  // Top-level PlasmicTos renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    analytics: makeNodeComponent("analytics"),
    pageHeader: makeNodeComponent("pageHeader"),
    navBar: makeNodeComponent("navBar"),
    pageFooter: makeNodeComponent("pageFooter"),

    // Metadata about props expected for PlasmicTos
    internalVariantProps: PlasmicTos__VariantProps,
    internalArgProps: PlasmicTos__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicTos;
/* prettier-ignore-end */
